<a href="https://colab.research.google.com/github/Aradhya6394/Artificial-Intelligence-2025/blob/main/Python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import
import numpy as np


In [ ]:
n_list=[1,2,8,5,6]

In [ ]:
print(n_list)

[1, 2, 8, 5, 6]


In [ ]:
numarray=np.array(n_list)

In [ ]:
numarray

array([1, 2, 8, 5, 6])

In [ ]:
len(numarray)

5

In [ ]:
# Accessing Array Elements.

In [ ]:
numarray[3]

np.int64(5)

In [ ]:
# Slicing

In [ ]:
numarray[1:3]

array([2, 8])

In [ ]:
numarray[-1]

np.int64(6)

In [ ]:
numarray

array([1, 2, 8, 5, 6])

In [ ]:
numarray[2:-1]

array([8, 5])

In [ ]:
numarray[1:5:2]

array([2, 5])

In [ ]:
numarray[::-1]

array([6, 5, 8, 2, 1])

In [ ]:
# Numpy Arithmetic

In [ ]:
numarray

array([1, 2, 8, 5, 6])

In [ ]:
numarray+12    # addition

array([13, 14, 20, 17, 18])

In [ ]:
numarray-4    # subtraction

array([-3, -2,  4,  1,  2])

In [ ]:
numarray*2   # multiplication

array([ 2,  4, 16, 10, 12])

In [ ]:
numarray/2    #divide

array([0.5, 1. , 4. , 2.5, 3. ])

In [ ]:
# simple Numpy Function

In [ ]:
np.sum(numarray)

np.int64(22)

In [ ]:
np.mean(numarray)

np.float64(4.4)

In [ ]:
np.max(numarray)

np.int64(8)

In [ ]:
np.min(numarray)

np.int64(1)

In [ ]:
# 2 one dimensional array

In [ ]:
arr1=np.array([4,7,12,6,7,9,8])
arr2=np.array([2,1,4,15,8,14,9])

In [ ]:
len(arr1)

7

In [ ]:
arr1+arr2

array([ 6,  8, 16, 21, 15, 23, 17])

In [ ]:
np.multiply(arr1,arr2)

array([  8,   7,  48,  90,  56, 126,  72])

In [ ]:
# 2D arays

In [ ]:
arr2d=np.array((arr1,arr2))

In [ ]:
arr2d

array([[ 4,  7, 12,  6,  7,  9,  8],
       [ 2,  1,  4, 15,  8, 14,  9]])

In [ ]:
arr2d[1,4]

np.int64(8)

In [ ]:
arr2d[0,2]

np.int64(12)

In [ ]:
# slicing

In [ ]:
arr2d

array([[ 4,  7, 12,  6,  7,  9,  8],
       [ 2,  1,  4, 15,  8, 14,  9]])

In [ ]:
arr2d[0:2,2:5]

array([[12,  6,  7],
       [ 4, 15,  8]])

In [ ]:
# check the dimension of the array

In [ ]:
arr2d.ndim

2

In [ ]:
arr1.ndim

1

In [ ]:
# chacke no of rows and column using Shape

In [ ]:
arr2d

array([[ 4,  7, 12,  6,  7,  9,  8],
       [ 2,  1,  4, 15,  8, 14,  9]])

In [ ]:
arr2d.shape

(2, 7)

In [ ]:
arr1

array([ 4,  7, 12,  6,  7,  9,  8])

In [ ]:
arr1.shape

(7,)

In [ ]:
# reshaping array

In [ ]:
print(arr1)


[ 4  7 12  6  7  9  8]


In [ ]:
arr1.reshape(7,1)

array([[ 4],
       [ 7],
       [12],
       [ 6],
       [ 7],
       [ 9],
       [ 8]])

In [ ]:
print(arr2d)

[[ 4  7 12  6  7  9  8]
 [ 2  1  4 15  8 14  9]]


In [ ]:
arr2d.reshape(7,2)

array([[ 4,  7],
       [12,  6],
       [ 7,  9],
       [ 8,  2],
       [ 1,  4],
       [15,  8],
       [14,  9]])

In [ ]:
# numpy functions on 2D array

In [ ]:
num2d=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [ ]:
print(num2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(np.max(num2d))

9


In [ ]:
print(np.min(num2d))

1


In [ ]:
print(np.max(num2d,axis=0))  # max value of each colomn

[7 8 9]


In [ ]:
print(np.max(num2d,axis=1))

[3 6 9]


In [ ]:
# searching on array

In [ ]:
price=np.array([29,34,28,90,35,89,100])

In [ ]:
print(price)

[ 29  34  28  90  35  89 100]


In [ ]:
print(np.where(price>90))

(array([6]),)


In [ ]:
print(np.where(price==90))

(array([3]),)


In [ ]:
# Sorting Array

In [ ]:
run=np.array([34,12,90,100,67,45,23,56])

In [ ]:
print(run)

[ 34  12  90 100  67  45  23  56]


In [ ]:
print(np.sort(run))

[ 12  23  34  45  56  67  90 100]


In [ ]:
print(np.flip(run)) # reverse array

[ 56  23  45  67 100  90  12  34]


In [ ]:
# filter array

In [ ]:
run[run>50]

array([ 90, 100,  67,  56])

In [ ]:
# creating array by special methods .

In [ ]:
print(np.linspace(1,10,5))  # generates the array values within that range
# (start,stop,how many values you want)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
print(np.arange(1,10,2)) #(start,stop,stepsize)

[1 3 5 7 9]


In [ ]:
# array of all zeroess

In [ ]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [ ]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# all arrays of ones

In [ ]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [ ]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# matrix Multiplication

In [ ]:
m1=np.array([[1,9,5],[3,6,2],[9,4,7]])

In [ ]:
m2=np.array([[3,9,2],[4,7,1],[7,2,6]])

In [ ]:
print(m1)


[[1 9 5]
 [3 6 2]
 [9 4 7]]


In [ ]:
print(m2)

[[3 9 2]
 [4 7 1]
 [7 2 6]]


In [ ]:
print(m1@m2)

[[ 74  82  41]
 [ 47  73  24]
 [ 92 123  64]]


In [ ]:
print(np.dot(m1,m2))

[[ 74  82  41]
 [ 47  73  24]
 [ 92 123  64]]


In [ ]:
# Dot Products

In [ ]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])

In [ ]:
print(np.dot(a1,a2))

32


In [ ]:
# create random element

In [ ]:
# 1D array
print(np.random.rand(6))

[0.22391495 0.92004139 0.5612077  0.38575247 0.60957789 0.64527106]


In [ ]:
# 2D array
print(np.random.rand(2,3))

[[0.30175418 0.16870756 0.04846116]
 [0.61610157 0.84959014 0.62201612]]


In [ ]:
print(np.random.randint(3,10,(2,4)))

[[8 9 7 6]
 [6 7 9 9]]


In [ ]:
print(np.random.randint(3,10,6))

[9 8 5 9 4 6]
